### ISSUE TITLE
update react to latest stable release (16.3.X)

### ISSUE THREAD

**Issue by lleifermann** [communicode/communikey-frontend#8]
The project is running with react 15.4.2. We should update to latest stable release  16.3.X

**Comment by svengreb** [comment]
### Benefits

Next to the fact that we keep the project up-to-date with latest bug fixes and performance improvements, this is a preparation for the new awesome™ async rendering feature and will allow us to make use of

* new the awesome™ [context API][dcapi]
* the the new awesome™ [lifecycle methods][dlcm] and moving away from the now deprecated ones `componentWillReceiveProps` and 
* the new awesome™  [`createRef`][drapi] and [`forwardRef`][dfrapi] API to migrate all forms placed in modals
* the new awesome™ [`StrictMode` component][dstm] to help to find possible future problems with async rendering

See the official [React 16.3 introduction blog post][bp] for more details.

[bp]: https://reactjs.org/blog/2018/03/29/react-v-16-3.html
[dstm]: https://reactjs.org/docs/strict-mode.html
[dlcm]: https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops
[dfrapi]: https://reactjs.org/docs/forwarding-refs.html
[drapi]: https://reactjs.org/docs/refs-and-the-dom.html
[dcapi]: https://reactjs.org/docs/context.html
